### ISSUE TITLE
Different folder for: "programdata\application\data\ssh"

### ISSUE THREAD

**Issue by QMSPS** [aJesus37/OpenSSH-Win-Config#10]
Hi,

I did just  try it myself to change the config and key location, from "programdata\ssh" to a other folder like "programdata\application\data\ssh". Do you ythink it's possible?

Kind regards,

**Comment by QMSPS** [comment]
I have already find a way, to make the impossible possible. I added a environment variable, with setting a different path for the variable "programdata". So now I can run multiple instances of SSHD.

Maybe you can integrate it: cmd /V /C "set programdata=$RUNFOLDER\REQ\SSH&& $RUNFOLDER\REQ\SSH\sshd.exe -f $RUNFOLDER\REQ\SSH\sshd_config"" -Description "QConnect SSH Daemon" -StartupType Automatic

**Comment by aJesus37** [comment]
Hello @QMSPS , sorry for the late reply.
I've spent a few hours trying to apply this feature, however, many of the service configuration is made either by the `install-sshd.ps1` or the sshd.exe itself when the service is started for the first time, which are both out of my direct control.

Can you please share the exact steps used to make this setting work?
I've tried setting up the service with a new config, but I didn't got it working, going always for the `C:\Programdata\ssh` folder.

**Comment by QMSPS** [comment]
Hi,

Also sorry for the late reply, people are busy this days so don't worry ;-)

For now I already build my own OpenSSH download and install tool. What I did is download the latest version like:
`Get-QHELP-Download-Zip -source "https://chocolatey.org/api/v2/package/openssh/" -destination ".\TEMP\SSH.zip" -folder ".\TEMP\SSH"`

This is downloading the Zip file and extracting it, after that I replace some text inside  the "install-sshd.ps1" (and others, for my situation) and than run the "install-sshd.ps1" file. What is required to change:

`Edit-QHELP-Replace-Text -path .\REQ\SSH\install-sshd.ps1 -find 'service sshd' -replace 'Service QConnect-SSHD'`

`Edit-QHELP-Replace-Text -path .\REQ\SSH\install-sshd.ps1 -find 'sc.exe privs sshd' -replace 'sc.exe privs QConnect-SSHD'`

`Edit-QHELP-Replace-Text -path .\REQ\SSH\install-sshd.ps1 -find 'New-Service -Name sshd -DisplayName "OpenSSH SSH Server" -BinaryPathName `"$sshdpath`" -Description $sshdDesc -StartupType Manual' -replace 'New-Service -Name "QConnect-SSHD" -DisplayName "QConnect SSH Server" -Description "QConnect only SSH Server" -BinaryPathName "cmd /V /C set programdata=$RUNFOLDER\DATA&& $RUNFOLDER\REQ\SSH\sshd.exe -f $RUNFOLDER\DATA\SSH\sshd_config" -StartupType Automatic'`


You see a lot of QHelp commands, thats because I totally don't like to write big code, what's used frequently over and over again. Zo I build a lot of Powershell modules, what will be build as encrypted DLL files to make coding the same code over and over again a history. (will place a open source version later)

The most important part is:
`"cmd /V /C set programdata=$RUNFOLDER\DATA&& $RUNFOLDER\REQ\SSH\sshd.exe -f $RUNFOLDER\DATA\SSH\sshd_config"`

For me the runfolder is: 
`$RUNFOLDER = "$Env:ProgramData\$COMPANYID\$SCRIPTID"`

I also find out, that if you install SSHD, from Microsoft Windows 2019 / 10, and you create a extra service and start it with these parameters and using the Microsoft OpenSSHD files that are installed on the system.  It's also working on as a extra service with a own folder.


I need it because I'm busy building I need a SSH server, that's not configured by some other existing SSHD server.

**Comment by aJesus37** [comment]
Hi @QMSPS, I'm glad you made it, and thanks for the detailed instruction!
Since you already accomplished your goal, and that your need is a bit specific, I'll then close this issue, but feel free to reopen it if you need anything!

Regards,
Jesus.
